apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: pedido-pod-cpu-stress
  namespace: app
  labels:
    app.kubernetes.io/name: pedido
    chaos-test: "true"
spec:
  mode: one
  selector:
    namespaces:
      - app
    labelSelectors:
      app: pedido
  stressors:
    cpu:
      workers: 1
      load: 80
  duration: "60s"
  scheduler:
    cron: "@every 10m"
